apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-apm
  labels:
    app: nodeapp-apm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp-apm
  template:
    metadata:
      labels:
        app: nodeapp-apm
    spec:
      containers:
      - name: nodeapp-apm
        image: docker.io/mariancraciunescu/the-example-app.nodejs
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 2
          successThreshold: 2
          failureThreshold: 3
        env:
        - name: APM_SERVER
          value: "apm-server"
        - name: APM_SERVER_PORT
          value: '8200'
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-apm
spec:
  type: NodePort
  ports:
    - nodePort: 32300
      port: 3000
      protocol: TCP
  selector:
    app: nodeapp-apm
